# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
    

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.7
    
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8

    
    - name: Checkout msr21
      uses: actions/checkout@v2
      with:
        repository: beirut-repository-mining/msr21
        path: .
        fetch-depth: 0
    
    - name: ls
      run: ls -R


    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3800 # Optional, default value is 3306. The port of host
        container port: 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'BugMining' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'GithubExamplePassword' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'GithubExampleUser' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'GithubExamplePassword' # Required if "mysql user" exists. The password for the "mysql user"

    - run: npm start
      shell: powershell

